$('.owl-carousel').owlCarousel({
    loop:true,
    margin:0,
    nav:false,
    responsive:{
        0:{
            items:3
        },
        600:{
            items:6
        },
        1000:{
            items:10
        }
    }
})